// <auto-generated />
using System;
using DistributedCache.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DistributedCache.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributedCache.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Laptop gaming 16GB RAM",
                            IsDeleted = false,
                            Name = "Laptop",
                            Price = 1299.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mouse inalambrico ergonomico",
                            IsDeleted = false,
                            Name = "Mouse",
                            Price = 29.99m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            Description = "Teclado mecanico RGB",
                            IsDeleted = false,
                            Name = "Teclado",
                            Price = 89.99m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 4,
                            Description = "Monitor 27 pulgadas 4K",
                            IsDeleted = false,
                            Name = "Monitor",
                            Price = 449.99m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 5,
                            Description = "Auriculares bluetooth con cancelacion de ruido",
                            IsDeleted = false,
                            Name = "Auriculares",
                            Price = 199.99m,
                            Stock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
